name: Upload changed files to S3 root (clean version)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install s3-deploy
        run: npm install -g s3-deploy

      - name: Deploy only changed files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          s3-deploy './**' \
            --bucket ${{ secrets.S3_BUCKET }} \
            --cwd . \
            --region ${{ secrets.AWS_REGION }} \
            --delete \
            --no-acl
