name: Upload to S3 root

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache workspace for S3 sync
        uses: actions/cache@v3
        with:
          path: .
          key: s3-sync-cache-${{ github.sha }}
          restore-keys: |
            s3-sync-cache-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 without ACLs
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
            --region ${{ secrets.AWS_REGION }} \
            --delete \
            --exact-timestamps \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore"
